disabled_rules:
  - multiple_closures_with_trailing_closure
  - orphaned_doc_comment
  - trailing_comma
opt_in_rules:
  - anyobject_protocol
  - array_init
  - closure_spacing
  - collection_alignment
  - contains_over_first_not_nil
  - convenience_type
  - empty_count
  - empty_string
  - empty_xctest_method
  - explicit_init
  - fallthrough
  - fatal_error_message
  - first_where
  - identical_operands
  - implicit_return
  - implicitly_unwrapped_optional
  - last_where
  - legacy_random
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - missing_docs
  - modifier_order
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - nimble_operator
  - no_extension_access_modifier
  - override_in_extension
  - pattern_matching_keywords
  - prohibited_super_call
  - quick_discouraged_call
  - redundant_nil_coalescing
  - redundant_type_annotation
  - sorted_first_last
  - toggle_bool
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - untyped_error_in_catch
  - unused_import
  - yoda_condition
excluded:
  - Packages/*/Package.swift
  - Packages/*/Tests
  - Tasktive/Models/CoreData
  - Tests
  - fastlane/SnapshotHelper.swift
type_name:
  min_length:
    warning: 2
identifier_name:
  min_length:
    warning: 2
  allowed_symbols: '_'
