# Snapfile

devices([
    "iPhone 8 Plus",
    "iPhone 13 Pro Max",
    "iPad Pro (12.9-inch) (5th generation)",
])

languages([
  "en-US",
])

scheme("MainFlowsUITests")
output_directory("./fastlane/screenshots/iOS")
clear_previous_screenshots(true)
override_status_bar(true)
launch_arguments([])
number_of_retries(0)
stop_after_first_error(true)
