name: CI
on:
  push:
    branches:
      - develop
      - "release/**"
      - "feature/**"

jobs:
  quality:
    name: Quality
    timeout-minutes: 15
    runs-on: macos-latest
    steps:
      - name: Git - Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
          submodules: recursive

      - name: Swift lint
        run: |
          python3 Scripts/swiftlint_checker/main.py
