name: CI
on:
  push:
    branches:
      - main
      - "release/**"
      - "feature/**"

jobs:
  quality:
    name: Quality
    timeout-minutes: 15
    runs-on: macos-12
    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Git - Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
          submodules: recursive

      - name: Swift lint
        run: |
          python3 Scripts/swiftlint_checker/main.py

  test:
    name: Test
    timeout-minutes: 15
    runs-on: macos-12
    needs: [quality]
    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Git - Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
          submodules: recursive

      - name: Setup - Xcode
        run: |
          sh Scripts/select_xcode_version.sh

      - name: Setup - Ruby and bundler dependencies
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0
          bundler-cache: true

      - name: Create token file
        run: |
          # No need to actually add the tokens in the test

          yarn generate-tokens

      - name: Test
        run: |
          yarn test:ios

  # deployIOS:
  #   name: deploy iOS
  #   timeout-minutes: 15
  #   runs-on: macos-latest
  #   needs: [test]
  #   if: contains(github.ref, 'refs/heads/release/') || github.ref == 'refs/heads/main'
  #   steps:
  #     - name: Git - Checkout
  #       uses: actions/checkout@v2
  #       with:
  #         ref: ${{ github.ref }}
  #         submodules: recursive

  #     - name: Setup - Xcode
  #       run: |
  #         sh Scripts/select_xcode_version.sh

  #     - name: Setup - Ruby and bundler dependencies
  #       uses: ruby/setup-ruby@v1
  #       with:
  #         ruby-version: 3.0
  #         bundler-cache: true
